name: "Points Bar"
description: "Generates a points/progress SVG bar"

inputs:
  points:
    description: "Points string separated with a / slash."
    required: true
  path:
    description: "File path to save the generated SVG to."
    required: true
  type:
    description: "Style of bar to generate; either bar or badge."
    default: "default"
    required: false
  bar-color:
    description: "Color to use for the points bar."
    required: false
  bar-background:
    description: "Background color for the points bar."
    required: false
  reverse:
    description: "Reverse the progress direction of the bar. i.e. Progress bar moves from right to left."
    default: false
    required: false

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: check
  color: green
