name: Update Points Bar

on:
  workflow_dispatch:

jobs:
  update:
    name: Update points bar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # switch to svg-build branch
      - run: git checkout svg-build || git checkout -b svg-build

      # generate random points
      - name: random points
        id: random-points
        run: |
            points=$((10 + $RANDOM % 80))"/100"
            echo "::set-output name=points::$points"

      # create points bar
      - name: points bar
        uses: markpatterson27/points-bar@v1
        with:
          points: ${{ steps.random-points.outputs.points }}
          path: '.github/icons/points-bar.svg'

      # create points badge
      - name: points badge
        uses: markpatterson27/points-bar@v1
        with:
          points: ${{ steps.random-points.outputs.points }}
          path: '.github/icons/points-badge.svg'
          type: 'badge'

      # create points bar with custom colors
      - name: points bar color
        uses: markpatterson27/points-bar@v1
        with:
          points: ${{ steps.random-points.outputs.points }}
          path: '.github/icons/points-bar-color.svg'
          bar-color: 'gold'
          bar-background: '#115544'
          font-color: '#BF5700'

      # create points bar with custom label
      - name: score bar
        uses: markpatterson27/points-bar@v1
        with:
          points: ${{ steps.random-points.outputs.points }}
          path: '.github/icons/points-bar-custom-label.svg'
          label: 'Score'

      # create points badge with custom label
      - name: autograde badge
        uses: markpatterson27/points-bar@v1
        with:
          points: ${{ steps.random-points.outputs.points }}
          path: '.github/icons/points-badge-custom-label.svg'
          type: 'badge'
          label: 'Autograde'

      # create wide points bar
      - name: wide points bar
        uses: markpatterson27/points-bar@v1
        with:
          points: ${{ steps.random-points.outputs.points }}
          path: '.github/icons/points-bar-wide.svg'
          width: 220

      # create points badge reversed
      - name: points badge reversed
        uses: markpatterson27/points-bar@v1
        with:
          points: ${{ steps.random-points.outputs.points }}
          path: '.github/icons/points-badge-reversed.svg'
          type: 'badge'
          bar-color: '#11BBCC'
          bar-background: '#88BBCC'
          reverse: true

      # commit and push activity icons if svg-builds have changed
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add '.github/icons/points-*.svg'
          git commit -m "Add/Update points bar" || exit 0
          git push origin svg-build
